---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# lmmsmsn

<!-- badges: start -->
<!-- badges: end -->

The goal of lmmsmsn is to fit scale mixture of skew-normal linear mixed models with possible within-subject dependence structure, using an EM-type algorithm.

## Installation

<!-- You can install the released version of lmmsmsn from [CRAN](https://CRAN.R-project.org) with: -->

<!-- ``` r -->
<!-- install.packages("lmmsmsn") -->
<!-- ``` -->

You can install lmmsmsn from GitHub with:

```r
library(devtools)
install_github("fernandalschumacher/lmmsmsn")
```

## Example

This is a basic example which shows you how to fit a SMSN-LMM:

```{r example}
library(lmmsmsn)
    dat1 <- as.data.frame(nlme::Orthodont)
    fm1 <- smsn.lmm(dat1,formFixed=distance ~ age,groupVar="Subject")
    fm1
    summary(fm1)
```

For more examples, see help(smsn.lmm).
